In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\chinm\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\chinm\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\chinm\anaconda3\lib\site-packages (from xgboost) (1.15.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../../data/hypertension.csv")

In [4]:
df.head()

,male,age,currentSmoker,cigsPerDay,BPMeds,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Risk
0,1,39,0,0.0,0.0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   male           4240 non-null   int64
 1   age            4240 non-null   int64
 2   currentSmoker  4240 non-null   int64
 3   cigsPerDay     4211 non-null   float64
 4   BPMeds         4187 non-null   float64
 5   diabetes       4240 non-null   int64
 6   totChol        4190 non-null   float64
 7   sysBP          4240 non-null   float64
 8   diaBP          4240 non-null   float64
 9   BMI            4221 non-null   float64
 10  heartRate      4239 non-null   float64
 11  glucose        3852 non-null   float64
 12  Risk           4240 non-null   int64
dtypes: float64(8), int64(5)
memory usage: 430.8 KB

In [6]:
df['cigsPerDay'].fillna(df['cigsPerDay'].median(),inplace=True)

C:\Users\chinm\AppData\Local\Temp\ipykernel_20204\1449433005.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cigsPerDay'].fillna(df['cigsPerDay'].median(),inplace=True)

In [11]:
df.describe()

,male,age,currentSmoker,cigsPerDay,BPMeds,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Risk
count,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4240.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,0.494104,8.944340,0.029245,0.025708,236.699523,132.354599,82.897759,25.799005,75.878981,81.963655,0.310613
std,0.495027,8.572942,0.500024,11.904777,0.168513,0.158280,44.327521,22.033300,11.910394,4.070775,12.025348,23.954335,0.462799
min,0.000000,32.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.077500,68.000000,71.000000,0.000000
50%,0.000000,49.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,1.000000,20.000000,0.000000,0.000000,262.000000,144.000000,90.000000,28.032500,83.000000,87.000000,1.000000
max,1.000000,70.000000,1.000000,70.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [8]:
df['BPMeds'].fillna(df['BPMeds'].median(),inplace=True)

C:\Users\chinm\AppData\Local\Temp\ipykernel_20204\3349902776.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BPMeds'].fillna(df['BPMeds'].median(),inplace=True)

In [9]:
df['totChol'].fillna(df['totChol'].mean(),inplace=True)

C:\Users\chinm\AppData\Local\Temp\ipykernel_20204\3526917815.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['totChol'].fillna(df['totChol'].mean(),inplace=True)

In [10]:
df['BMI'].fillna(df['BMI'].median(),inplace=True)

C:\Users\chinm\AppData\Local\Temp\ipykernel_20204\4225218744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(df['BMI'].median(),inplace=True)

In [12]:
df['glucose'].fillna(df['glucose'].mean(),inplace=True)

C:\Users\chinm\AppData\Local\Temp\ipykernel_20204\622919608.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['glucose'].fillna(df['glucose'].mean(),inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   male           4240 non-null   int64
 1   age            4240 non-null   int64
 2   currentSmoker  4240 non-null   int64
 3   cigsPerDay     4240 non-null   float64
 4   BPMeds         4240 non-null   float64
 5   diabetes       4240 non-null   int64
 6   totChol        4240 non-null   float64
 7   sysBP          4240 non-null   float64
 8   diaBP          4240 non-null   float64
 9   BMI            4240 non-null   float64
 10  heartRate      4239 non-null   float64
 11  glucose        4240 non-null   float64
 12  Risk           4240 non-null   int64
dtypes: float64(8), int64(5)
memory usage: 430.8 KB

In [14]:
df = df.drop_duplicates()

In [16]:
df.shape

(4240, 13)

In [17]:
df.columns

Index(['male', 'age', 'currentSmoker', 'cigsPerDay', 'BPMeds', 'diabetes',
       'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose', 'Risk'],
      dtype='object')

In [28]:
df['sysBP'] = df['sysBP'].replace(0, np.nan)
df['diaBP'] = df['diaBP'].replace(0, np.nan)

In [37]:
X = df[['male', 'age', 'cigsPerDay', 'BPMeds',
       'totChol',  'BMI', 'heartRate']]
y = df['Risk']

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [50]:
rf = RandomForestClassifier(n_estimators=200,max_depth=8,random_state=42,class_weight='balanced')
xg = XGBClassifier(random_state = 42,
    eval_metric = "logloss",
    use_label_encoder = False)

In [42]:
rf.fit(X_train,y_train)
xg.fit(X_train,y_train)
y_pred_rf = rf.predict(X_test)
y_pred_xg = xg.predict(X_test)
rf_accuracy = accuracy_score(y_test,y_pred_rf)
xg_accuracy = accuracy_score(y_test,y_pred_xg)
print("Rf accuracy", rf_accuracy)
print("xg accuracy", xg_accuracy)

Rf accuracy 0.7382075471698113
xg accuracy 0.7370283018867925

In [36]:
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf.feature_importances_
})

feature_importance = feature_importance.sort_values(by='importance', ascending=False)
feature_importance

      feature  importance
5       sysBP    0.489372
6       diaBP    0.288978
1         age    0.053897
7         BMI    0.052993
3      BPMeds    0.039153
4     totChol    0.030167
8   heartRate    0.025803
2  cigsPerDay    0.014994
0        male    0.004641

In [51]:
from sklearn.model_selection import RandomizedSearchCV
param_dist_rf = {
    "n_estimators": np.arange(100, 500, 50),
    "max_depth": [None, 4, 6, 8, 10],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

param_dist_xgb = {
    "n_estimators": np.arange(100, 400, 50),
    "max_depth": [3, 4, 5, 6, 7],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 0.9, 1.0],
    "colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "gamma": [0, 0.1, 0.2, 0.3]
}

In [52]:
rf_random = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist_rf,
    n_iter=20,              # number of combinations to try
    cv=5,                   # 5-fold cross-validation
    verbose=2,
    random_state=42,
    n_jobs=-1
)

rf_random.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(class_weight='balanced',
                                                    max_depth=8,
                                                    n_estimators=200,
                                                    random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'max_depth': [None, 4, 6, 8, 10],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': array([100, 150, 200, 250, 300, 350, 400, 450])},
                   random_state=42, verbose=2)

In [53]:
print("Best Params:", rf_random.best_params_)
print("Best Score:", rf_random.best_score_)

best_rf = rf_random.best_estimator_

Best Params: {'n_estimators': np.int64(350), 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': None}
Best Score: 0.7293586351610255

In [47]:
xgb_random = RandomizedSearchCV(
    estimator=xg,
    param_distributions=param_dist_xgb,
    n_iter=25,
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

xgb_random.fit(X_train, y_train)

print("Best Params:", xgb_random.best_params_)
print("Best Score:", xgb_random.best_score_)

best_xgb = xgb_random.best_estimator_

Fitting 5 folds for each of 25 candidates, totalling 125 fits
Best Params: {'subsample': 0.9, 'n_estimators': np.int64(200), 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0, 'colsample_bytree': 0.7}
Best Score: 0.746169318927279

In [54]:
rf_pred = best_rf.predict(X_test)
xgb_pred = best_xgb.predict(X_test)

print("RF Accuracy:", accuracy_score(y_test, rf_pred))
print("XGB Accuracy:", accuracy_score(y_test, xgb_pred))

RF Accuracy: 0.7264150943396226
XGB Accuracy: 0.7441037735849056

In [55]:
from sklearn.metrics import classification_report
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.79      0.84      0.81       595
           1       0.55      0.47      0.50       253

    accuracy                           0.73       848
   macro avg       0.67      0.65      0.66       848
weighted avg       0.72      0.73      0.72       848

In [63]:
y_prob = rf_random.predict_proba(X_test)[:, 1]

# Try lower threshold
y_pred = (y_prob > 0.32).astype(int)

In [64]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.61      0.71       595
           1       0.45      0.75      0.56       253

    accuracy                           0.65       848
   macro avg       0.65      0.68      0.63       848
weighted avg       0.73      0.65      0.66       848

[[360 235]
 [ 64 189]]